default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: ehe_health_development

test:
  <<: *default
  database: ehe_health_test

production:
  <<: *default
  database: ehe_health_production
  username: ehe_health
  password: <%= ENV['EHE_HEALTH_DATABASE_PASSWORD'] %>